const routes = {
  home: { title:'About NFMS', crumb:'Home', side:'About NFMS', template: homePage },
  about: { title:'About NFMS', crumb:'About NFMS', side:'About NFMS', template: aboutPage },
  monitoring: { title:'Forest Monitoring', crumb:'Forest Monitoring', side:'Forest Monitoring', template: monitoringPage },
  mrv: { title:'MRV & Climate', crumb:'MRV & Climate', side:'MRV & Climate', template: mrvPage },
  maps: { title:'Forest Data & Maps', crumb:'Forest Data & Maps', side:'Forest Data & Maps', template: mapsPage },
  reporting: { title:'Reporting & Submissions', crumb:'Reporting & Submissions', side:'Reporting & Submissions', template: reportingPage },
  knowledge: { title:'Data & Knowledge', crumb:'Data & Knowledge', side:'Data & Knowledge', template: knowledgePage },
  quality: { title:'Quality & Transparency', crumb:'Quality & Transparency', side:'Quality & Transparency', template: qualityPage },
  governance: { title:'Safeguards & Governance', crumb:'Safeguards & Governance', side:'Safeguards & Governance', template: governancePage },
  news: { title:'News & Events', crumb:'News & Events', side:'News & Events', template: newsPage },
  contact: { title:'Contact & Support', crumb:'Contact & Support', side:'Contact & Support', template: contactPage }
};

const featured = [
  {title:'Latest forest monitoring update', text:'Latest forest cover, land-cover and forest-change intelligence.', route:'monitoring', icon:'fa-tree'},
  {title:'Recent forest alert summary', text:'View current alerts and prioritised areas for field verification.', route:'monitoring', icon:'fa-triangle-exclamation'},
  {title:'Latest NFMS publication', text:'Browse the newest reports, assessments and technical publications.', route:'reporting', icon:'fa-file-lines'},
  {title:'Restoration highlight', text:'Explore restoration monitoring, sites, progress and evidence.', route:'maps', icon:'fa-seedling'}
];
const partners=['KEFRI','DRSRS','RCMRD','KMD','KWS','WRA','KALRO','NEMA','KNBS','KSA','NLC','KTDA-MS','Universities','County Governments'];
const news=[
  {date:'06 OCT',title:'NFMS-FIP interface and data catalogue update',text:'The portal is being aligned around a clearer landing page, functional modules and quality-controlled data publishing.'},
  {date:'25 SEP',title:'Forest monitoring and UAV verification',text:'Field verification workflows continue to connect satellite change detection, UAV mapping and mobile surveys.'},
  {date:'12 SEP',title:'NFMS-FIP collaboration and data submissions',text:'Partner institutions can submit datasets through the structured validation and review workflow.'}
];

function shell(title, crumb, body){
  return `<div class="breadcrumb"><i class="fa-solid fa-house"></i> &nbsp; Home &nbsp;›&nbsp; ${crumb}</div><div class="content-inner"><h1>${title}</h1>${body}</div>`;
}
function homePage(){
  return shell('About NFMS','About NFMS',`
    <div class="home-intro">
      <div>
        <h2>What is NFMS?</h2>
        <p class="lead">The National Forest Monitoring System (NFMS) is a coordinated national framework for collecting, managing, analysing and sharing forest information to support sustainable forest management, climate action and informed decision-making in Kenya.</p>
        <p>NFMS-FIP brings satellite Earth observation, national forest inventory, UAV verification, field surveys, GIS, carbon and climate information into a common information environment with clear quality, governance and publication controls.</p>
      </div>
      <div class="mission-card"><strong>Why NFMS?</strong><div class="mission-list"><div class="mission-item"><i class="fa-solid fa-check"></i><span>Reliable forest data</span></div><div class="mission-item"><i class="fa-solid fa-check"></i><span>Evidence-based decisions</span></div><div class="mission-item"><i class="fa-solid fa-check"></i><span>Climate change mitigation</span></div><div class="mission-item"><i class="fa-solid fa-check"></i><span>Sustainable forest management</span></div></div></div>
    </div>
    <h2>Main NFMS Functional Areas</h2>
    <div class="feature-grid">
      ${['Forest Monitoring|Monitor forest cover, change, deforestation, degradation, alerts and fire.|monitoring|fa-tree','MRV & Climate|Access forest carbon, GHG, MRV, FREL/FRL and REDD+ information.|mrv|fa-cloud','Forest Data & Maps|Explore interactive maps, dashboards, restoration, biodiversity and county forest information.|maps|fa-map','Data & Knowledge|Discover datasets, metadata, data standards, downloads, APIs and knowledge resources.|knowledge|fa-database'].map(x=>{let [t,p,r,i]=x.split('|');return `<a class="feature-card" href="#${r}" data-route="${r}"><div class="icon"><i class="fa-solid ${i}"></i></div><h3>${t}</h3><p>${p}</p></a>`}).join('')}
    </div>
    <h2>Featured Forest Information</h2>
    <div class="highlight-grid">${featured.map(f=>`<a class="highlight-card" href="#${f.route}" data-route="${f.route}"><div class="label">Featured</div><h3><i class="fa-solid ${f.icon}"></i> ${f.title}</h3><p>${f.text}</p><div class="arrow">→</div></a>`).join('')}</div>
    <h2>Partners &amp; Collaboration</h2>
    <p class="section-note">NFMS-FIP is strengthened through institutional collaboration, data sharing, technical review and contribution from national agencies, research organisations, counties and other partners.</p>
    <div class="partner-strip">${partners.map(p=>`<span class="partner-pill">${p}</span>`).join('')}</div>
    <h2>News &amp; Events</h2>
    <div class="news-list">${news.slice(0,3).map(n=>`<a href="#news" data-route="news" class="news-item"><div><h3>${n.title}</h3><p>${n.text}</p></div><div class="date-badge">${n.date.split(' ')[0]}<small>${n.date.split(' ')[1]}</small></div></a>`).join('')}</div>
    <div class="cta-bar"><div><strong>Data submission to NFMS-FIP</strong><div class="section-note">Upload → Validate → Review → Approve → Publish → Display on NFMS</div></div><a class="primary-btn" href="#reporting" data-route="reporting">Open submission workflow <i class="fa-solid fa-arrow-right"></i></a></div>
  `);
}
function aboutPage(){return shell('About NFMS','About NFMS',`<h2>National Forest Monitoring System (NFMS)</h2><p class="lead">NFMS provides a national framework for consistent forest monitoring, assessment, reporting, knowledge management and data sharing.</p><h2>NFMS Framework</h2><p>It connects monitoring technologies, inventory systems, institutional responsibilities, data standards, quality assurance and public information services through NFMS-FIP.</p><h2>Institutional &amp; Governance Framework</h2><p>Roles are organised around data providers, technical review, KFS system administration, publication controls, safeguards and transparent access to approved information.</p><h2>Policies &amp; Legal Framework</h2><p>Applicable forestry, environmental, geospatial, information-management, climate and data-sharing requirements should be reflected in the platform's governance and publication rules.</p><h2>Partners</h2><div class="partner-strip">${partners.map(p=>`<span class="partner-pill">${p}</span>`).join('')}</div>`)}
function monitoringPage(){return shell('Forest Monitoring','Forest Monitoring',`<p class="lead">Integrated monitoring from satellite observation through UAV and field verification.</p><div class="feature-grid"><a class="feature-card" href="#monitoring"><div class="icon"><i class="fa-solid fa-satellite"></i></div><h3>Forest Cover Mapping</h3><p>Track national and county forest cover using standardised spatial products.</p></a><a class="feature-card" href="#monitoring"><div class="icon"><i class="fa-solid fa-chart-line"></i></div><h3>Forest Change</h3><p>Detect and interpret changes in forest extent and condition.</p></a><a class="feature-card" href="#monitoring"><div class="icon"><i class="fa-solid fa-bell"></i></div><h3>Forest Alerts</h3><p>Prioritise current disturbances for verification and response.</p></a><a class="feature-card" href="#monitoring"><div class="icon"><i class="fa-solid fa-fire"></i></div><h3>Fire Monitoring</h3><p>Monitor fire activity, hotspots and supporting evidence.</p></a></div><h2>Monitoring Workflow</h2><div class="workflow">${['Satellite Earth Observation','AI / Automated Change Detection','Forest Alerts & Prioritisation','UAV Verification & Detailed Mapping','Mobile Field Survey & Ground Verification','QA/QC & Data Validation'].map((s,i)=>`<div class="step"><div class="num">${i+1}</div><b>${s}</b></div>`).join('')}</div><div class="cta-bar"><div><strong>Next: PostGIS → NFMS-FIP → Maps / Dashboards / Reports / MRV</strong></div><a class="secondary-btn" href="#maps" data-route="maps">Explore forest data &amp; maps</a></div>`)}
function mrvPage(){return shell('MRV & Climate','MRV & Climate',`<p class="lead">Access forest carbon, greenhouse gas, MRV, FREL/FRL and REDD+ information.</p><div class="feature-grid"><a class="feature-card" href="#mrv"><div class="icon"><i class="fa-solid fa-leaf"></i></div><h3>Carbon Stocks</h3><p>National and subnational forest carbon information.</p></a><a class="feature-card" href="#mrv"><div class="icon"><i class="fa-solid fa-cloud-arrow-up"></i></div><h3>GHG &amp; MRV</h3><p>Monitoring, reporting and verification evidence for climate action.</p></a><a class="feature-card" href="#mrv"><div class="icon"><i class="fa-solid fa-scale-balanced"></i></div><h3>FREL / FRL</h3><p>Reference levels and supporting forest emissions information.</p></a><a class="feature-card" href="#mrv"><div class="icon"><i class="fa-solid fa-tree-city"></i></div><h3>REDD+</h3><p>Information supporting REDD+ implementation and reporting.</p></a></div>`)}
function mapsPage(){return shell('Forest Data & Maps','Forest Data & Maps',`<p class="lead">Explore spatial information and decision-support resources across Kenya's forest landscape.</p><div class="feature-grid"><a class="feature-card" href="#maps"><div class="icon"><i class="fa-solid fa-map"></i></div><h3>Interactive Forest Map</h3><p>Explore forest boundaries, monitoring layers and supporting datasets.</p></a><a class="feature-card" href="#maps"><div class="icon"><i class="fa-solid fa-chart-column"></i></div><h3>Dashboards</h3><p>View indicators, trends and operational monitoring summaries.</p></a><a class="feature-card" href="#maps"><div class="icon"><i class="fa-solid fa-seedling"></i></div><h3>Restoration Monitoring</h3><p>Track restoration sites, actions and evidence.</p></a><a class="feature-card" href="#maps"><div class="icon"><i class="fa-solid fa-frog"></i></div><h3>Biodiversity &amp; Ecosystems</h3><p>Connect forest monitoring with biodiversity and ecosystem information.</p></a></div>`)}
function reportingPage(){return shell('Reporting & Submissions','Reporting & Submissions',`<p class="lead">Controlled data submission and publication pathway for authorised contributors.</p><h2>Data Submission Workflow</h2><div class="workflow">${['Upload','Validate','Review','Approve','Publish','Display on NFMS'].map((s,i)=>`<div class="step"><div class="num">${i+1}</div><b>${s}</b></div>`).join('')}</div><div class="role-grid"><div class="role-card"><span class="role-badge">Public user</span><h3>Open information access</h3><ul><li>View maps</li><li>Search datasets</li><li>Download approved datasets</li><li>View dashboards</li><li>Read publications</li></ul></div><div class="role-card"><span class="role-badge">Data Provider</span><h3>Institutional data contribution</h3><ul><li>Upload datasets</li><li>Enter metadata</li><li>Update datasets</li><li>Submit datasets for review</li></ul></div><div class="role-card"><span class="role-badge">Technical Reviewer / NTC</span><h3>Technical quality control</h3><ul><li>Review submitted data</li><li>Check metadata</li><li>Check spatial quality</li><li>Check completeness</li><li>Approve or reject submissions</li></ul></div><div class="role-card"><span class="role-badge">KFS NFMS Super User</span><h3>Catalogue administration</h3><ul><li>Publish approved datasets</li><li>Manage users</li><li>Manage categories</li><li>Manage permissions</li><li>Maintain the catalogue</li></ul></div></div><h2>Authorised user path</h2><p><strong>Login → Add Dataset → Upload → Metadata → Submit for Review → Technical Validation → Publish</strong></p><div class="cta-bar"><div><strong>Ready to submit data?</strong><div class="section-note">Use the login control in the header to enter the authorised workspace.</div></div><button class="primary-btn" id="openLoginInline">Login to submit <i class="fa-solid fa-right-to-bracket"></i></button></div>`)}
function knowledgePage(){return shell('Data & Knowledge','Data & Knowledge',`<p class="lead">A structured catalogue for discovering and using trusted forest information.</p><table class="table"><thead><tr><th>Resource</th><th>Purpose</th><th>Access</th></tr></thead><tbody><tr><td>Datasets</td><td>Discover published forest and environmental datasets.</td><td>Public / authorised</td></tr><tr><td>Metadata</td><td>Describe source, quality, lineage, spatial reference and stewardship.</td><td>Public</td></tr><tr><td>Data standards</td><td>Support ISO 19115, EPSG, UTF-8 and consistent catalogue practice.</td><td>Public</td></tr><tr><td>Downloads</td><td>Download approved data products and publications.</td><td>Public / authorised</td></tr><tr><td>APIs</td><td>Connect systems and dashboards to machine-readable services.</td><td>Authorised</td></tr><tr><td>Knowledge resources</td><td>Guidance, SOPs, methodologies and technical references.</td><td>Public</td></tr></tbody></table><h2>Data Catalogue</h2><div class="api-box">GET /api/catalogue<br>GET /api/datasets/{id}<br>GET /api/metadata/{id}<br>POST /api/submissions</div>`)}
function qualityPage(){return shell('Quality & Transparency','Quality & Transparency',`<p class="lead">Quality assurance and transparent publication controls help keep NFMS information reliable and traceable.</p><div class="feature-grid"><div class="feature-card"><div class="icon"><i class="fa-solid fa-clipboard-check"></i></div><h3>Completeness</h3><p>Required fields, metadata and supporting evidence are checked before publication.</p></div><div class="feature-card"><div class="icon"><i class="fa-solid fa-location-crosshairs"></i></div><h3>Spatial Quality</h3><p>Geometry, coordinate reference systems and positional consistency are reviewed.</p></div><div class="feature-card"><div class="icon"><i class="fa-solid fa-clock-rotate-left"></i></div><h3>Versioning</h3><p>Dataset updates and publication states can be traced through controlled versions.</p></div><div class="feature-card"><div class="icon"><i class="fa-solid fa-eye"></i></div><h3>Transparency</h3><p>Approved public information is discoverable with clear stewardship and provenance.</p></div></div>`)}
function governancePage(){return shell('Safeguards & Governance','Safeguards & Governance',`<p class="lead">Roles, permissions, safeguards and institutional accountability are built into the information lifecycle.</p><div class="role-grid"><div class="role-card"><h3>Public user</h3><p>Access only approved public information.</p></div><div class="role-card"><h3>Data Provider</h3><p>Contribute and maintain institutional datasets through controlled submission.</p></div><div class="role-card"><h3>Technical Reviewer / NTC</h3><p>Perform technical checks and approve or reject submissions.</p></div><div class="role-card"><h3>KFS NFMS Super User</h3><p>Administer users, permissions, categories and publication controls.</p></div></div>`)}
function newsPage(){return shell('News & Events','News & Events',`<p class="lead">Latest NFMS-FIP announcements, activities and important forest information events.</p><div class="news-list">${news.map(n=>`<article class="news-item"><div><h3>${n.title}</h3><p>${n.text}</p></div><div class="date-badge">${n.date.split(' ')[0]}<small>${n.date.split(' ')[1]}</small></div></article>`).join('')}</div><div class="cta-bar"><div><strong>More news and events</strong><div class="section-note">Use this section for the full institutional news and events archive.</div></div><button class="secondary-btn" type="button" onclick="window.scrollTo({top:document.body.scrollHeight,behavior:'smooth'})">View full section</button></div>`)}
function contactPage(){return shell('Contact & Support','Contact & Support',`<p class="lead">Need access, data support or technical help?</p><div class="role-grid"><div class="role-card"><h3>NFMS-FIP Support</h3><p>Email: <a href="mailto:nfms@kenyaforestservice.org" style="color:#2575df">nfms@kenyaforestservice.org</a></p><p>For catalogue, submission, metadata and access issues.</p></div><div class="role-card"><h3>Data Submission Support</h3><p>Authorised data providers should contact the NFMS technical administrator when a submission requires review or publication support.</p></div></div>`)}

function render(route){
  if(!routes[route]) route='home';
  const r=routes[route];
  document.getElementById('contentPanel').innerHTML=r.template();
  document.getElementById('sideTitle').textContent=r.side;
  document.querySelectorAll('[data-route]').forEach(el=>el.classList.toggle('active',el.dataset.route===route));
  document.querySelectorAll('.side-links a').forEach((el,i)=>{el.classList.toggle('active',el.dataset.route===route && i===0)});
  document.title=`${r.title} | NFMS-FIP`;
  bindInlineLogin();
  window.scrollTo({top:document.querySelector('.page-shell').offsetTop-145,behavior:'smooth'});
}
function currentRoute(){return (location.hash||'#home').slice(1).split('?')[0] || 'home'}
window.addEventListener('hashchange',()=>render(currentRoute()));

document.addEventListener('click',e=>{
  const routeEl=e.target.closest('[data-route]');
  if(routeEl){ e.preventDefault(); const route=routeEl.dataset.route; if(location.hash!==`#${route}`) location.hash=route; else render(route); document.getElementById('mobileNav').classList.remove('show'); }
});

const modal=document.getElementById('loginModal');
function openModal(){modal.classList.add('show');modal.setAttribute('aria-hidden','false');document.getElementById('loginUser').focus()}
function closeModal(){modal.classList.remove('show');modal.setAttribute('aria-hidden','true')}
document.getElementById('loginOpen').addEventListener('click',openModal);document.getElementById('loginClose').addEventListener('click',closeModal);modal.addEventListener('click',e=>{if(e.target===modal)closeModal()});
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});
document.getElementById('loginSubmit').addEventListener('click',()=>{const role=document.getElementById('loginRole').value;closeModal();location.hash='reporting';setTimeout(()=>alert(role==='provider'?'Data Provider workspace selected. Connect this UI to your authentication/API before production use.':role==='reviewer'?'Technical Reviewer / NTC workspace selected.':'KFS NFMS Super User workspace selected.'),100)})
function bindInlineLogin(){const b=document.getElementById('openLoginInline');if(b)b.addEventListener('click',openModal)}

document.getElementById('mobileMenuToggle').addEventListener('click',()=>document.getElementById('mobileNav').classList.toggle('show'));
const searchBar=document.getElementById('searchBar'),searchInput=document.getElementById('siteSearch'),searchResults=document.getElementById('searchResults');
document.getElementById('searchToggle').addEventListener('click',()=>{searchBar.classList.toggle('show');if(searchBar.classList.contains('show'))searchInput.focus()});document.getElementById('searchClose').addEventListener('click',()=>searchBar.classList.remove('show'));
const searchable=[['About NFMS','about'],['Forest Monitoring','monitoring'],['Forest Alerts','monitoring'],['MRV & Climate','mrv'],['Forest Data & Maps','maps'],['Reporting & Submissions','reporting'],['Data & Knowledge','knowledge'],['Quality & Transparency','quality'],['Safeguards & Governance','governance'],['News & Events','news'],['Contact & Support','contact']];
searchInput.addEventListener('input',()=>{const q=searchInput.value.trim().toLowerCase();searchResults.innerHTML=q?searchable.filter(([t])=>t.toLowerCase().includes(q)).map(([t,r])=>`<a href="#${r}" data-route="${r}" class="search-result">${t}</a>`).join(''):''});

document.getElementById('year').textContent=new Date().getFullYear();
render(currentRoute());
